### ISSUE TITLE
Make an example application with sangria backend and react-relay frontend

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria-relay#1]

**Comment by siderakis** [comment]
:+1:

**Comment by OlegIlyenko** [comment]
Here is the first example play app that uses react-relay and sangria: https://github.com/ykad4/sangria-relay-playground. Big thanks to @ykad4!

**Comment by ykad4** [comment]
My pleasure. I am looking forward to your feedback.

**Comment by ykad4** [comment]
I think you can close it now! :tada:

**Comment by OlegIlyenko** [comment]
yep, it's now sangria-relay playground is now available here: http://try-relay.sangria-graphql.org
