### ISSUE TITLE
graphiql throwing errors for InputObjectTypes

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria-relay#13]
```scala
  val GeometryInputType = InputObjectType[Geometry](
    "Geometry",
    List(
    InputField("type", StringType),
    InputField("coordinates", ListInputType(FloatType))
  ))
// mutation input fields
  inputFields = List(
      InputField("type", StringType),
      InputField("geometry", GeometryInputType)
)
```

Causes an error:

```
Error: Introspection must provide input type for arguments. at invariant (http://cdn.jsdelivr.net/graphiql/0.4.2/graphiql.min.js:10:12143) at r (http://cdn.jsdelivr.net/graphiql/0.4.2/graphiql.min.js:12:23289) at http://cdn.jsdelivr.net/graphiql/0.4.2/graphiql.min.js:12:25929 at http://cdn.jsdelivr.net/graphiql/0.4.2/graphiql.min.js:10:12860 at Array.reduce (native) at keyValMap (http://cdn.jsdelivr.net/graphiql/0.4.2/graphiql.min.js:10:12824) at _ (http://cdn.jsdelivr.net/graphiql/0.4.2/graphiql.min.js:12:25865) at _typeDefinition.GraphQLInputObjectType.fields (http://cdn.jsdelivr.net/graphiql/0.4.2/graphiql.min.js:12:25547) at resolveMaybeThunk (http://cdn.jsdelivr.net/graphiql/0.4.2/graphiql.min.js:11:9452) at e._createClass.value (http://cdn.jsdelivr.net/graphiql/0.4.2/graphiql.min.js:11:19455)
```

**Comment by OlegIlyenko** [comment]
@chandu0101 I think I reproduced an issue but defining and using input **and** output types with name `Geometry`. Can you please verify that it's the case in your app?

GraphQL has a only global namespace for all types withing the schema regardless of the type kind (scalar, input type, output type, etc.). this means that you need to rename either input our output type.

Sangria does not detect these cases at the moment, but ideally it should warn when there is a name collision between incompatible types. I created an issue of this: https://github.com/sangria-graphql/sangria/issues/117

**Comment by chandu0101** [comment]
yeah renaming worked like charm, thank you :)

**Comment by OlegIlyenko** [comment]
perfect!

**Comment by OlegIlyenko** [comment]
FYI, I implemented the validation. Ho you will not be able to create a schema with error like this:

> Type name 'Geometry' is used for several conflicting GraphQL type kinds: ObjectType, InputObjectType. Conflict found in an argument 'points' defined in field 'foo' of 'Query' type.

**Comment by chandu0101** [comment]
cool thank you :)
