### ISSUE TITLE
How to get the *Edge type descriptor

### ISSUE THREAD

**Issue by gre** [sangria-graphql/sangria-relay#14]
I was testing http://try-relay.sangria-graphql.org/ and found in the example schema this:

```scala
type IntroduceShipPayload {
  ship: Ship
  faction: Faction
  clientMutationId: String!
}
```

however in the Relay documentation, it is expected you also return the `*Edge` that was created in the `*Connection`.

see here: https://facebook.github.io/relay/docs/guides-mutations.html#range-add-example

AFAIK it's even mandatory to be able to express a RANGE_ADD mutation in Relay.

So I guess you should add it to the playground, do you think it is easy to add? we were wondering with @mandubian if it is trivial or not, in Sangria Relay, to have access to the type descriptor of the `*Edge` type. Is there something I missed, like an helper to access this type?

Thanks

**Comment by OlegIlyenko** [comment]
`Connection.definition` returns the [`ConnectionDefinition`](https://github.com/sangria-graphql/sangria-relay/blob/225e12a0593ead1c7b1802f5dae1cd97b82d6f25/src/main/scala/sangria/relay/Connection.scala#L146-L146) which has a GrapQL types (or a descriptors) for an `*Edge` and `*Connection` types. Do you mean this one?

Unfortunately I can't find anything about returning an edge type as a result of mutation in the relay spec [here](https://facebook.github.io/relay/docs/graphql-mutations.html#content) or [here](https://facebook.github.io/relay/graphql/mutations.htm#sec-Mutation-fields). Maybe it's a recent addition to relay that haven't made it to the spec yet? (although I haven't seen any recent additions to the reference implementation)

**Comment by gre** [comment]
sounds good. we will try this. thanks
