### ISSUE TITLE
[Support] Relay Modern

### ISSUE THREAD

**Issue by namdq1969** [sangria-graphql/sangria-relay#20]
I want to pick scala for my new graphql project. May I ask whether this project fully support for Relay Modern? Thanks.

https://facebook.github.io/relay/docs/relay-modern.html

**Comment by DaveDeCaprio** [comment]
I am using sangria-relay with Relay Modern and everything appears to be working fine.  I'm just a user who has built a small application, so this isn't an official answer, but it is working for me.  The server spec for Relay doesn't change with Relay Modern as far as I can tell.

**Comment by OlegIlyenko** [comment]
I collected some feedback from different users and looks like no changes are needed on the server side to support relay modern. It should work out-of-the-box. 

Please feel free to reopen this issue in case you found some issues integrating with replay modern.
