### ISSUE TITLE
Multiple node types

### ISSUE THREAD

**Issue by DaveDeCaprio** [sangria-graphql/sangria-relay#21]
I'm having a problem once I have more than 1 node type in 
    Node.possibleNodeTypes[Repository, Node](AType, BType)

In the example this function only returns 1 node type, (Ship), but then I can't query for the others.  The code uses a type parameter called Abstract, which I can't seem to find the definition of.

Do you have an example of how to have multiple node types with Node.definition()

**Comment by OlegIlyenko** [comment]
You can find an example in the tests (though you need to explicitly provide `Node.possibleNodeTypes` only if you are not overriding `id` field in concrete `Node` implementations):

https://github.com/sangria-graphql/sangria-relay/blob/77874af7aac5b0813a99f68d7b3e0681433b0a52/src/test/scala/sangria/relay/starWars/StarWarsSchema.scala#L88-L92

This test demonstrates a query used with 2 node types (`Ship` and `Faction`) :

https://github.com/sangria-graphql/sangria-relay/blob/77874af7aac5b0813a99f68d7b3e0681433b0a52/src/test/scala/sangria/relay/starWars/StarWarsConnectionSpec.scala#L321-L389

**Comment by DaveDeCaprio** [comment]
Excellent, thanks.  It turns out my problem was user error.  I had a type mismatch with an Option/non-Option type and the error message wasn't led me astray.  Anyway, it's all working now.

Thanks for letting me know I don't need possibleNodeTypes also.  Always nice to save some boilerplate.
