### ISSUE TITLE
ArrayIndexOutOfBoundsException when using an invalid global id

### ISSUE THREAD

**Issue by stephane-debart** [sangria-graphql/sangria-relay#28]
In some cases when an invalid global Id is used in graphQL query, an ArrayIndexOutOfBoundsException is thrown by the DatatypeConverter used in Base64.scala.
This exception should be caught and a proper WrongGlobalId should be sent.

**Comment by Malax** [comment]
I opened two pull requests some time ago that should fix this issue. However,
 (https://github.com/sangria-graphql/sangria-relay/pull/27)[the last one] is not in 1.2.2. Can you verify that the changed fixes your problem? If so, we might be able to convince @OlegIlyenko to create new release. :)

**Comment by stephane-debart** [comment]
yes this change fix my issue.

**Comment by Malax** [comment]
@OlegIlyenko Are we able to put out a new release? I would also love to drop my custom build with the buxfix and use an official one. :)

**Comment by OlegIlyenko** [comment]
Just released in https://github.com/sangria-graphql/sangria-relay/releases/tag/v1.3.1 Thanks again for the PR! 👍

**Comment by stephane-debart** [comment]
Just integrated 1.3.1. This works fine.
Thanks to both of you.
