### ISSUE TITLE
Where I can check an example with Sub queries? 

### ISSUE THREAD

**Issue by tkgreg** [sangria-graphql/sangria-relay#30]
I've checked examples and it's quite clear how to create schema for models managed by the same Repo class. what is the main approach when I want for an example work with multiple models what are not strongly tied up to each other. Can I have some kind of sub queries in QueryType object?

**Comment by OlegIlyenko** [comment]
I think this example might help you:

https://github.com/sangria-graphql/sangria/blob/ff057f24affc307918d2c99c569b15b8452b1c58/src/test/scala/sangria/execution/ContextPassingSpec.scala

It is a variation of a cake pattern for a context object. Do you think it would help in your scenario?

**Comment by tkgreg** [comment]
Yeah, thank you for the quick response!
