### ISSUE TITLE
Adding totalCount field in Connection

### ISSUE THREAD

**Issue by srenault** [sangria-graphql/sangria-relay#33]
Hello,

It would be interesting to have `totalCount` defined at `Connection` level, especially when you have a connection to a database. It would save us from performing an extra count request.
What do you think?

**Comment by OlegIlyenko** [comment]
Sure thing, you can provide additional connection fields though `connectionFields` argument when you are defining it with `Connection.definition`/`Connection.definitionWithEdge`. Here is a small example:

https://github.com/sangria-graphql/sangria-relay/blob/4b915f12b11ef3d1002eedf23efeec1ed5f10e9b/src/test/scala/sangria/relay/ConnectionSpec.scala#L59-L66
