### ISSUE TITLE
Create a trait to automatically add the raw ID of an object to a type

### ISSUE THREAD

**Issue by boosh** [sangria-graphql/sangria-relay#5]
I need to be able to access the raw ID of a returned object on the client so I can pass it to a third-party service. At the moment, I'm base64 decoding the global ID and extracting the object ID to pass through. However, because I want to keep my components dumb, I'm doing this in a parent and then overwriting the `id` with the raw ID before passing it to a child as a prop value.

From the discussion at https://github.com/facebook/relay/issues/191 it seems fiddling with the `id` like this isn't a good idea since it might impact relay's caching, etc. The recommended approach is to add an extra field to the response containing the raw ID.

Since this could be quite a common usecase, it'd be handy if there was a trait that would automatically add the raw ID to the type, perhaps under a `_rawID` field.

**Comment by OlegIlyenko** [comment]
`Node.definition` does not rely on inheritance at the moment. If you look at the example:

https://github.com/sangria-graphql/sangria-relay/blob/31fa60342090f368a3f2823ada820db1b18eb578/src/test/scala/sangria/relay/starWars/StarWarsSchema.scala#L87

It just creates a field definition and `InterfaceType` which you can use on concrete objects. It's pretty easy to add additional `rawId` type to them. For example, here is how you can do it for `Ship` type:

```scala
val ShipType: ObjectType[Unit, Ship] = ObjectType(
    "Ship",
    "A ship in the Star Wars saga",
    fields[Unit, Ship](
      Node.globalIdField("Ship"),
      Field("rawId", StringType, resolve = _.value.id),
      Field("name", OptionType(StringType), Some("The name of the ship."), resolve = _.value.name)),
    interfaces[Unit, Ship](nodeInterface))
```

If you want to do it in more generic way, then I would suggest you to define a small helper function, that would create 2 fields: `id` (which is `GrlobalId`) and `rawId`:

```scala
def idFields[T : Identifiable](name: String) = fields[Unit, T](
    Node.globalIdField(name),
    Field("rawId", StringType, resolve = ctx => implicitly[Identifiable[T]].id(ctx.value))
  )
```

Then `ShipType` can use it like this:

```scala
  val ShipType: ObjectType[Unit, Ship] = ObjectType(
    "Ship",
    "A ship in the Star Wars saga",
    idFields[Ship]("Ship") ++
    fields[Unit, Ship](
      Field("name", OptionType(StringType), Some("The name of the ship."), resolve = _.value.name)),
    interfaces[Unit, Ship](nodeInterface))
```

Based on my experience I would say, that it's better to treat internal IDs of objects as a blackbox on the client. They often can change after, for instance, a database migration (unless you are using something like `UUID` and do not rely on DB to generate these IDs for you). If you are giving an ID to a third-party application of service (like an external calendar service in your example), then I would consider it a good practice to create an additional `externalId` or `referenceId` for your entities which you are exposing to third-party applications.

**Comment by boosh** [comment]
> If you are giving an ID to a third-party application of service (like an external calendar service in your example), then I would consider it a good practice to create an additional externalId or referenceId for your entities which you are exposing to third-party applications.

Excellent idea. I'll generate a UUID server-side and pass it as a dedicated field to avoid all this fiddling around with IDs. I guess we don't need this ticket then...
