### ISSUE TITLE
2.0.0 compatible release?

### ISSUE THREAD

**Issue by kubukoz** [sangria-graphql/sangria-relay#52]
Hi! I can see sangria is already released as 2.0.0, and this module isn't - but the dependency has been updated. Would you mind making a release of this library too? Or is 1.x compatible with 2.x of the core?

**Comment by bengraygh** [comment]
@yanns I guess #50 closes this.

**Comment by yanns** [comment]
I might need to push another release.
In the meantime, https://github.com/sangria-graphql/sangria-relay/releases/tag/v2.0.0-M2 should work. You can force the update of the transitive dependency to use sangria 2.0.0.

**Comment by kubukoz** [comment]
Yeah, that version seems to work, and even sbt-missinglink didn't find any incompatibilities :)

**Comment by yanns** [comment]
I've nevertheless published the [2.0.0 release](https://github.com/sangria-graphql/sangria-relay/releases/tag/v2.0.0).

**Comment by kubukoz** [comment]
Thanks!
