### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by aleksandersumowski** [sangria-graphql/sangria-relay#55]
readme mentions that the documentation on the main project website, but there is nothing usefule there

https://www.google.com/search?hl=en&q=site%3Ahttps%3A%2F%2Fsangria%2Dgraphql.github.io%20relay

**Comment by yanns** [comment]
fixed by https://github.com/sangria-graphql/sangria-relay/commit/4cc381bfa0d7a6f26427dfc7854dc22c6b5934ea
